<a href="https://colab.research.google.com/github/AhmedAboushanab/Machine-learning-models/blob/main/k_nearest_neighbors_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [14]:
dataset = pd.read_csv('Total.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


**Encoding categorical output**

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

## Splitting the dataset into the Training set and Test set

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [17]:
print(X_train)

[[35.099    0.13618 59.21308  5.55174]
 [11.84388  0.33033 71.30551 13.59813]
 [12.28782  1.75342 79.69508  1.58847]
 ...
 [20.79023  0.50593 44.67264 14.03005]
 [18.83287  2.71046 69.46467  2.20033]
 [73.42044  5.1794  19.7647   1.62367]]


In [18]:
print(y_train)

[3 3 2 3 0 2 0 3 1 0 2 2 1 3 2 3 3 3 3 3 3 1 3 2 2 1 3 2 3 3 2 3 0 2 2 3 3
 3 3 2 0 3 3 2 3 3 2 3 3 1 2 3 3 2 3 3 3 3 0 2 2 2 0 3 0 3 0 0 3 1 3 2 2 2
 3 3 3 3 3 3 2 1 2 1 3 1 3 0 1 3 3 1 3 3 3 3 3 2 3 3 2 0 2 3 3 3 3 0 3 3 2
 3 1 3 2 3 0 3 2 2 3 3 3 3 2 1 3 2 1 3 3 0 3 2 3 1 2 1 0 1 3 3 0 2 3 3 2 3
 3 2 3 2 3 3 1 2 3 3 3 2 2 1 1 3 3 2 3 3 3 3 2 3 2 1 3 3 3 0 2 1 3 0 3 2 3
 3 1 3 3 2 1 1 3 2 2 2 0 3 3 3 2 3 3 2 2 1 2 2 3 2 3 3 3 3 2 2 1 3 1 3 3 2
 1 2 1 2 2 1 0 0 2 1 2 0 0 1 3 2 3 3 3 2 3 3 1 1 3 3 2 1 1 2 3 2 0 2 3 1 0
 2 1 0 0 3 3 3 3 3 2 2 3 3 3 3 3 3 1 1 3 2 0 0 0 2 3 3 3 0 0 0 3 3 1 2 3 1
 0 3 1 3 1 0 0 1 2 3 1 3 0 3 0 3 3 1 2 1 1 2 3 2 2 3 3 3 2 3 3 1 0 0 3 3 3
 0 2 1 3 3 1 3 2 2 2 3 3 3 3 3 1 0 2 0 3 3 3 3 3 3 3 3 3 3 2 3 3 0 3 3 0 3
 0 1 2 1 3 3 0 3 3 3 0 2 3 1 3 1 3 0 3 1 0 2 3 3 2 3 3 2 1 3 2 3 2 3 2 3 3
 3 2 2 1 0 3 3 0 2 0 3 2 0 3 3 2 3 3 3 3 3 1 2 1 1 3 1 2 3 3 3 3 3 2 3 2 0
 3 2 3 0 2 2 1 2 3 3 2 3 3 2 3 2 2 3 0 3 1 3 1 1 3 1 1 3 0 3 2 3 0 2 3 2 3
 1 3 1 0 2 2 3 1 3 2 0 3 

In [19]:
print(X_test)

[[7.79753000e+00 3.24340000e-01 6.32256000e+01 2.27862400e+01]
 [3.50761900e+01 1.10357400e+01 3.49278600e+01 1.89602100e+01]
 [1.34241600e+01 3.22970000e-01 7.35436600e+01 1.24903000e+01]
 [2.75913500e+01 1.31290000e-01 4.94358900e+01 2.27516000e+01]
 [3.29918500e+01 4.57120000e-01 5.25883300e+01 1.31542400e+01]
 [2.82982100e+01 1.88280000e-01 6.56251600e+01 4.31795000e+00]
 [4.32355600e+01 2.34400000e-02 5.43904000e+01 2.35061000e+00]
 [1.01278700e+01 2.77750000e-01 6.03279500e+01 2.91392500e+01]
 [2.55689600e+01 7.21970000e-01 6.76151500e+01 2.13103000e+00]
 [1.71865600e+01 7.28970000e-01 6.13929300e+01 2.06750900e+01]
 [1.65443500e+01 9.84600000e-02 6.39513300e+01 1.94058600e+01]
 [2.05863500e+01 2.11000000e-01 4.94521500e+01 2.80032100e+01]
 [1.59237400e+01 7.65453000e+00 7.58920800e+01 3.90550000e-01]
 [1.35252000e+00 4.60000000e-04 7.51406200e+01 1.84954200e+01]
 [3.33548200e+01 1.71049000e+00 6.07188000e+01 1.88315000e+00]
 [1.44363800e+01 3.62470000e-01 7.45970200e+01 1.030809

In [20]:
print(y_test)

[3 1 3 3 3 3 3 3 3 3 3 3 1 3 2 3 3 1 1 0 1 3 3 2 2 2 2 3 3 2 1 3 3 3 3 3 3
 3 2 2 2 2 3 2 3 2 3 2 3 3 3 1 3 3 3 3 2 3 3 0 2 2 2 2 2 2 2 3 2 3 3 2 3 3
 2 1 1 1 0 3 0 2 3 2 3 2 0 3 0 3 3 2 0 0 1 1 3 3 3 3 2 3 1 3 1 2 3 2 3 2 2
 1 1 3 3 2 2 2 2 1 2 3 3 1 3 3 3 0 3 3 3 3 3 3 3 3 3 3 3 1 3 0 2 3 2 2 3 3
 3 1 2 1 3 0 2 3 2 3 3 3 3 3 3 3 2 1 2 3 1 0 3 0 3 1 0 3 2 3 2 3 3 1 3 3 3
 3 2 2 3 3 3 1 0 2 3 0 3 0 2 3 3 3 3 1 2 1 2 3 3 2 2 1 3 3 3 3 2 3 2 3 2 3
 2 3 3 3 1 3 1 2 3 0 3 3 2 1 3 0 1 3 2 1 3 2 3 1 2 3]


## Training the K-NN model on the Training set

In [21]:
from sklearn.neighbors import KNeighborsClassifier
classifier =  KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

## Predicting the Test set results

In [22]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 3]
 [0 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [2 3]
 [3 3]
 [2 3]
 [3 3]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [3 2]
 [3 3]
 [3 3]
 [1 1]
 [3 1]
 [0 0]
 [1 1]
 [1 3]
 [3 3]
 [0 2]
 [2 2]
 [2 2]
 [0 2]
 [3 3]
 [3 3]
 [3 2]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 2]
 [0 2]
 [2 2]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 3]
 [2 3]
 [1 1]
 [2 3]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [0 3]
 [3 3]
 [3 0]
 [3 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [1 2]
 [3 2]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [1 2]
 [2 3]
 [3 3]
 [3 2]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [2 3]
 [0 0]
 [1 2]
 [2 3]
 [2 2]
 [3 3]
 [2 2]
 [2 0]
 [2 3]
 [2 0]
 [3 3]
 [2 3]
 [1 2]
 [3 0]
 [1 0]
 [3 1]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [1 3]
 [1 1]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [3 2]
 [2 2]
 [1 1]
 [1 1]
 [3 3]
 [3 3]
 [2 2]
 [0 2]
 [3 2]
 [2 2]
 [1 1]
 [0 2]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [3 3]
 [2 3]
 [2 0]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [1 0]
 [3 2]

## Making the Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  9   2   5   3]
 [  3  24   3   5]
 [ 11   6  32  16]
 [  2   2  15 110]]


0.7056451612903226