<a href="https://colab.research.google.com/github/AhmedAboushanab/Machine-learning-models/blob/main/Level_3_taxa_Logistic_Regression_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Total-L3.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

**Encoding categorical output**

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [4]:
print(y)

[3 0 2 2 3 0 3 3 2 1 1 3 0 0 3 3 0 3 3 3 2 3 1 3 3 2 3 3 3 3 3 3 3 1 3 3 2
 2 3 1 2 3 3 3 0 1 3 2 1 1 2 3 1 2 2 2 3 3 3 0 3 3 3 0 1 1 3 3 3 0 1 1 3 3
 0 0 2 3 2 3 2 3 0 2 0 2 3 3 3 1 3 3 1 3 2 3 2 1 3 3 3 1 3 3 2 1 1 2 3 3 3
 2 3 3 1 3 3 3 3 2 3 3 2 1 3 3 1 3 0 2 0 3 3 3 3 3 0 3 1 3 2 3 1 2 3 2 0 3
 3 3 3 1 1 2 1 0 1 3 2 3 2 3 0 2 2 2 1 2 2 2 3 3 0 3 3 3 2 2 2 3 3 2 3 3 2
 0 3 3 1 2 0 3 1 3 3 1 2 2 3 1 2 3 2 3 3 3 3 3 3 1 1 2 3 3 3 1 2 1 1 3 0 1
 3 3 1 2 0 2 3 1 3 3 2 1 3 0 1 0 2 2 2 3 3 2 0 3 3 2 0 3 0 1 3 3 3 2 2 3 3
 1 3 1 3 3 3 3 2 3 3 0 3 3 2 2 0 3 3 3 2 2 2 3 3 3 2 3 3 0 3 3 2 3 3 3 1 1
 0 3 3 1 2 3 3 2 3 3 3 3 1 3 3 2 2 3 0 3 3 0 2 3 2 3 3 3 2 1 3 2 2 3 1 0 0
 3 3 2 2 1 1 2 0 1 1 3 1 2 3 3 3 3 3 3 3 2 1 3 3 2 3 1 3 1 3 3 3 0 3 3 3 3
 3 3 3 3 3 3 0 3 3 3 3 3 3 3 3 3 2 3 3 2 2 3 3 1 3 3 1 3 3 3 3 2 3 3 1 3 1
 3 2 3 2 1 1 1 2 3 3 3 3 3 3 1 2 0 3 3 2 3 3 3 3 3 2 0 3 0 3 3 2 2 3 3 2 2
 3 1 0 3 0 2 3 3 2 3 3 3 3 3 3 2 3 1 2 3 3 1 2 3 2 3 3 3 1 1 3 3 3 2 3 2 0
 3 3 0 0 3 1 1 3 3 2 3 3 

## Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [6]:
print(X_train)

[[6.049445e+01 7.123050e+00 2.827982e+01 4.720800e-01 4.763600e-01]
 [6.058091e+01 1.192676e+01 2.600190e+01 1.411000e-01 6.373000e-02]
 [6.332390e+00 3.630700e-01 2.930531e+01 5.595700e-01 1.008800e-01]
 ...
 [6.317682e+01 3.090800e-01 3.577642e+01 4.623600e-01 3.807000e-02]
 [5.898015e+01 5.050040e+00 1.833387e+01 4.797200e-01 0.000000e+00]
 [7.036849e+01 2.026042e+01 7.222120e+00 1.129420e+00 3.157000e-02]]


In [7]:
print(y_train)

[3 3 1 1 1 2 2 3 3 3 1 0 3 3 2 0 2 3 3 1 3 0 1 3 3 3 2 1 3 3 1 3 1 1 0 1 2
 3 3 0 1 1 3 0 3 3 3 1 2 3 1 1 2 2 2 3 3 3 1 1 3 2 1 3 3 2 1 3 3 3 3 1 1 2
 1 3 3 2 1 1 3 2 3 0 3 3 3 0 1 3 2 3 1 2 3 1 3 1 3 3 3 2 1 0 3 2 3 3 3 3 3
 1 3 3 1 0 2 2 3 3 3 3 0 1 2 3 3 3 0 2 3 3 3 3 3 1 3 3 3 2 3 3 3 1 3 2 3 2
 2 2 3 1 2 3 2 2 1 2 1 1 0 1 3 3 0 3 2 3 3 3 3 2 1 3 3 0 3 3 0 3 3 3 1 0 1
 3 0 1 3 3 2 0 3 3 3 3 3 3 3 2 3 2 3 1 3 3 2 0 2 2 0 2 3 3 3 3 1 0 3 1 3 3
 2 1 3 3 3 1 2 3 3 3 0 1 3 3 0 0 1 1 3 3 2 2 1 3 3 1 3 2 3 3 3 3 3 1 1 3 2
 0 2 2 3 3 3 0 1 3 3 3 3 0 2 2 3 2 3 2 3 1 3 3 3 3 3 2 3 1 0 3 3 0 3 2 2 2
 3 3 3 2 3 3 2 2 2 3 2 2 3 2 3 3 0 3 3 0 3 3 3 1 1 3 2 3 3 2 0 0 2 3 2 2 2
 3 3 3 2 2 2 3 3 1 1 2 2 0 1 1 2 3 2 2 1 3 2 2 0 3 2 2 3 2 1 3 0 3 3 3 3 2
 3 3 2 3 2 3 1 1 2 3 3 2 2 3 3 3 2 3 2 3 3 3 3 0 2 3 2 2 2 2 3 3 3 1 3 3 3
 0 2 1 0 3 3 3 2 3 0 3 1 3 3 3 0 2 0 2 2 2 3 3 0 0 3 3 3 0 2 0 2 2 0 1 3 0
 3 3 1 2 2 3 2 2 3 0 2 2 3 1 2 0 0 2 3 2 2 3 2 2 1 1 3 0 1 3 2 1 3 3 3 3 3
 1 2 3 2 1 1 2 3 1 1 3 2 

In [8]:
print(X_test)

[[7.030597e+01 1.151193e+01 1.289688e+01 1.477990e+00 3.323000e-02]
 [2.217808e+01 1.667790e+00 6.822255e+01 4.481180e+00 1.250000e-03]
 [4.205322e+01 9.031110e+00 4.681473e+01 1.229200e+00 2.283000e-02]
 ...
 [3.105221e+01 1.483600e-01 6.432448e+01 4.527000e-02 4.900000e-04]
 [6.660927e+01 1.184625e+01 1.856356e+01 1.100900e-01 1.016000e-02]
 [3.185581e+01 2.670048e+01 2.374339e+01 6.878000e-02 3.558220e+00]]


In [9]:
print(y_test)

[3 2 3 2 1 3 3 3 3 2 3 1 2 3 1 3 3 1 3 3 3 3 3 3 3 2 3 2 1 3 2 3 0 3 2 3 3
 3 3 1 3 2 3 0 1 2 2 3 3 3 3 0 3 1 3 2 2 1 1 2 1 3 3 3 1 2 3 3 1 3 2 1 2 3
 3 1 1 0 2 3 2 2 0 2 3 2 0 3 2 1 3 3 2 0 3 1 3 3 2 3 2 1 2 3 3 0 1 3 1 3 2
 3 0 2 3 3 3 3 2 3 0 0 3 1 2 3 1 2 2 2 1 3 2 2 3 2 2 3 2 3 3 3 2 1 2 3 2 3
 3 1 3 3 0 3 3 3 3 2 3 0 2 3 2 3 3 3 3 3 2 2 3 3 3 1 1 3 3 3 3 2 0 3 3 3 2
 2 3 3 3 2 3 3 2 3 3 2 0 3 2 2 0 3 0 2 1 2 3 3 1 3 3 3 3 3 2 2 1 3 3 3 3 3
 3 2 2 2 2 3 3 0 1 2 2 3 3 1 2 3 0 3 2 2 3 3 1 0 3 0]


## Training the Logistic Regression model on the Training set

In [10]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Predicting the Test set results

In [11]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 3]
 [2 2]
 [3 3]
 [2 2]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 2]
 [3 3]
 [1 1]
 [3 2]
 [3 3]
 [1 1]
 [2 3]
 [3 3]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [2 3]
 [3 3]
 [3 3]
 [2 3]
 [3 2]
 [3 3]
 [2 2]
 [0 1]
 [3 3]
 [3 2]
 [3 3]
 [1 0]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [2 2]
 [3 3]
 [2 0]
 [1 1]
 [3 2]
 [0 2]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 0]
 [3 3]
 [1 1]
 [3 3]
 [2 2]
 [2 2]
 [1 1]
 [2 1]
 [3 2]
 [2 1]
 [3 3]
 [3 3]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [2 3]
 [0 1]
 [3 3]
 [3 2]
 [0 1]
 [0 2]
 [2 3]
 [3 3]
 [1 1]
 [2 1]
 [0 0]
 [0 2]
 [3 3]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [3 3]
 [3 2]
 [2 0]
 [3 3]
 [2 2]
 [2 1]
 [3 3]
 [2 3]
 [2 2]
 [2 0]
 [3 3]
 [0 1]
 [3 3]
 [3 3]
 [3 2]
 [3 3]
 [2 2]
 [1 1]
 [0 2]
 [3 3]
 [3 3]
 [2 0]
 [1 1]
 [3 3]
 [1 1]
 [3 3]
 [2 2]
 [3 3]
 [2 0]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [3 3]
 [0 0]
 [3 0]
 [3 3]
 [1 1]
 [2 2]
 [2 3]
 [2 1]
 [2 2]
 [3 2]
 [2 2]
 [1 1]
 [3 3]
 [2 2]
 [3 2]
 [3 3]
 [2 2]
 [0 2]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [2 2]

## Making the Confusion Matrix

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  9   1   7   4]
 [  4  19   8   3]
 [ 11   1  34  22]
 [  0   1  15 109]]


0.6895161290322581