<a href="https://colab.research.google.com/github/AhmedAboushanab/Machine-learning-models/blob/main/Level_3_taxa_random_forest_classification_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Random Forest Classification

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Total-L3.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


**Encoding categorical output**

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

## Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [5]:
print(X_train)

[[6.049445e+01 7.123050e+00 2.827982e+01 4.720800e-01 4.763600e-01]
 [6.058091e+01 1.192676e+01 2.600190e+01 1.411000e-01 6.373000e-02]
 [6.332390e+00 3.630700e-01 2.930531e+01 5.595700e-01 1.008800e-01]
 ...
 [6.317682e+01 3.090800e-01 3.577642e+01 4.623600e-01 3.807000e-02]
 [5.898015e+01 5.050040e+00 1.833387e+01 4.797200e-01 0.000000e+00]
 [7.036849e+01 2.026042e+01 7.222120e+00 1.129420e+00 3.157000e-02]]


In [6]:
print(y_train)

[3 3 1 1 1 2 2 3 3 3 1 0 3 3 2 0 2 3 3 1 3 0 1 3 3 3 2 1 3 3 1 3 1 1 0 1 2
 3 3 0 1 1 3 0 3 3 3 1 2 3 1 1 2 2 2 3 3 3 1 1 3 2 1 3 3 2 1 3 3 3 3 1 1 2
 1 3 3 2 1 1 3 2 3 0 3 3 3 0 1 3 2 3 1 2 3 1 3 1 3 3 3 2 1 0 3 2 3 3 3 3 3
 1 3 3 1 0 2 2 3 3 3 3 0 1 2 3 3 3 0 2 3 3 3 3 3 1 3 3 3 2 3 3 3 1 3 2 3 2
 2 2 3 1 2 3 2 2 1 2 1 1 0 1 3 3 0 3 2 3 3 3 3 2 1 3 3 0 3 3 0 3 3 3 1 0 1
 3 0 1 3 3 2 0 3 3 3 3 3 3 3 2 3 2 3 1 3 3 2 0 2 2 0 2 3 3 3 3 1 0 3 1 3 3
 2 1 3 3 3 1 2 3 3 3 0 1 3 3 0 0 1 1 3 3 2 2 1 3 3 1 3 2 3 3 3 3 3 1 1 3 2
 0 2 2 3 3 3 0 1 3 3 3 3 0 2 2 3 2 3 2 3 1 3 3 3 3 3 2 3 1 0 3 3 0 3 2 2 2
 3 3 3 2 3 3 2 2 2 3 2 2 3 2 3 3 0 3 3 0 3 3 3 1 1 3 2 3 3 2 0 0 2 3 2 2 2
 3 3 3 2 2 2 3 3 1 1 2 2 0 1 1 2 3 2 2 1 3 2 2 0 3 2 2 3 2 1 3 0 3 3 3 3 2
 3 3 2 3 2 3 1 1 2 3 3 2 2 3 3 3 2 3 2 3 3 3 3 0 2 3 2 2 2 2 3 3 3 1 3 3 3
 0 2 1 0 3 3 3 2 3 0 3 1 3 3 3 0 2 0 2 2 2 3 3 0 0 3 3 3 0 2 0 2 2 0 1 3 0
 3 3 1 2 2 3 2 2 3 0 2 2 3 1 2 0 0 2 3 2 2 3 2 2 1 1 3 0 1 3 2 1 3 3 3 3 3
 1 2 3 2 1 1 2 3 1 1 3 2 

In [7]:
print(X_test)

[[7.030597e+01 1.151193e+01 1.289688e+01 1.477990e+00 3.323000e-02]
 [2.217808e+01 1.667790e+00 6.822255e+01 4.481180e+00 1.250000e-03]
 [4.205322e+01 9.031110e+00 4.681473e+01 1.229200e+00 2.283000e-02]
 ...
 [3.105221e+01 1.483600e-01 6.432448e+01 4.527000e-02 4.900000e-04]
 [6.660927e+01 1.184625e+01 1.856356e+01 1.100900e-01 1.016000e-02]
 [3.185581e+01 2.670048e+01 2.374339e+01 6.878000e-02 3.558220e+00]]


In [8]:
print(y_test)

[3 2 3 2 1 3 3 3 3 2 3 1 2 3 1 3 3 1 3 3 3 3 3 3 3 2 3 2 1 3 2 3 0 3 2 3 3
 3 3 1 3 2 3 0 1 2 2 3 3 3 3 0 3 1 3 2 2 1 1 2 1 3 3 3 1 2 3 3 1 3 2 1 2 3
 3 1 1 0 2 3 2 2 0 2 3 2 0 3 2 1 3 3 2 0 3 1 3 3 2 3 2 1 2 3 3 0 1 3 1 3 2
 3 0 2 3 3 3 3 2 3 0 0 3 1 2 3 1 2 2 2 1 3 2 2 3 2 2 3 2 3 3 3 2 1 2 3 2 3
 3 1 3 3 0 3 3 3 3 2 3 0 2 3 2 3 3 3 3 3 2 2 3 3 3 1 1 3 3 3 3 2 0 3 3 3 2
 2 3 3 3 2 3 3 2 3 3 2 0 3 2 2 0 3 0 2 1 2 3 3 1 3 3 3 3 3 2 2 1 3 3 3 3 3
 3 2 2 2 2 3 3 0 1 2 2 3 3 1 2 3 0 3 2 2 3 3 1 0 3 0]


## Training the Random Forest Classification model on the Training set

In [9]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

## Predicting the Test set results

In [10]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 3]
 [0 2]
 [3 3]
 [2 2]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 2]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [1 1]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [2 3]
 [3 3]
 [3 3]
 [2 3]
 [3 2]
 [3 3]
 [1 2]
 [0 1]
 [3 3]
 [3 2]
 [3 3]
 [0 0]
 [3 3]
 [0 2]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [2 2]
 [3 3]
 [2 0]
 [1 1]
 [2 2]
 [0 2]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 0]
 [3 3]
 [0 1]
 [3 3]
 [0 2]
 [2 2]
 [1 1]
 [1 1]
 [3 2]
 [1 1]
 [3 3]
 [2 3]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [2 3]
 [0 1]
 [3 3]
 [3 2]
 [0 1]
 [0 2]
 [2 3]
 [3 3]
 [1 1]
 [1 1]
 [0 0]
 [0 2]
 [3 3]
 [0 2]
 [2 2]
 [0 0]
 [2 2]
 [3 3]
 [2 2]
 [2 0]
 [3 3]
 [3 2]
 [0 1]
 [3 3]
 [1 3]
 [2 2]
 [0 0]
 [3 3]
 [0 1]
 [3 3]
 [3 3]
 [3 2]
 [3 3]
 [2 2]
 [1 1]
 [0 2]
 [3 3]
 [3 3]
 [1 0]
 [1 1]
 [3 3]
 [1 1]
 [3 3]
 [2 2]
 [3 3]
 [1 0]
 [2 2]
 [1 3]
 [3 3]
 [3 3]
 [1 3]
 [2 2]
 [3 3]
 [0 0]
 [0 0]
 [3 3]
 [1 1]
 [2 2]
 [2 3]
 [0 1]
 [2 2]
 [3 2]
 [2 2]
 [0 1]
 [3 3]
 [2 2]
 [3 2]
 [3 3]
 [1 2]
 [0 2]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [2 2]

## Making the Confusion Matrix

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 15   2   2   2]
 [  9  22   2   1]
 [ 16   5  31  16]
 [  1   3  18 103]]


0.6895161290322581