<a href="https://colab.research.google.com/github/AhmedAboushanab/Machine-learning-models/blob/main/Logistic_Regression_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Total.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

**Encoding categorical output**

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[2 1 0 1 1 3 3 2 0 3 0 3 1 3 3 3 1 3 3 1 2 1 3 3 3 3 3 3 3 2 0 3 0 1 1 0 3
 3 2 2 1 3 2 3 3 3 3 2 0 2 2 2 3 3 3 3 3 3 2 3 2 3 3 3 2 3 3 3 3 3 2 0 0 3
 3 1 3 3 3 2 3 3 2 3 0 3 3 3 1 3 2 2 2 3 3 3 1 1 3 3 0 3 3 3 3 3 2 3 3 0 3
 0 1 0 3 1 3 3 2 3 0 2 0 3 3 3 2 1 1 3 1 1 3 1 0 0 2 3 3 1 2 2 1 3 3 3 0 0
 2 1 2 0 0 3 2 3 2 3 1 2 1 3 3 3 2 1 2 3 2 1 3 3 1 2 0 3 1 3 1 2 2 3 2 1 3
 2 2 2 3 3 2 2 1 2 3 3 2 3 3 3 1 3 3 3 2 2 1 0 3 3 2 3 3 0 2 2 3 3 2 3 1 3
 3 1 2 1 2 2 3 3 2 2 1 3 3 0 3 1 2 3 2 3 0 3 3 2 2 3 2 3 1 3 3 3 0 2 3 3 2
 2 3 3 1 3 2 1 0 3 1 0 3 1 0 3 2 2 1 3 1 3 3 1 0 1 3 3 2 3 3 3 1 3 3 0 3 3
 3 2 3 2 2 3 3 2 3 2 2 3 3 2 2 3 3 1 3 2 0 1 0 2 3 3 2 3 3 3 3 1 2 2 2 2 2
 3 3 3 3 3 2 3 2 0 1 1 2 3 2 3 1 3 3 3 3 3 1 3 3 3 3 3 2 0 1 3 2 0 3 2 3 3
 3 3 3 1 3 1 3 2 2 3 3 3 1 3 3 1 2 1 3 2 3 3 2 1 3 3 3 1 3 0 2 3 3 3 3 0 3
 0 1 2 1 3 1 2 3 3 3 1 3 0 2 3 3 1 3 3 3 2 3 0 2 1 2 2 3 3 3 3 2 1 2 1 3 3
 1 3 2 2 2 3 3 3 3 2 3 3 3 0 3 2 1 2 3 3 3 1 3 3 3 0 0 2 2 2 2 0 3 3 2 3 0
 1 3 3 2 3 3 1 3 2 3 3 3 

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train)

[[35.099       0.13618    59.21308     5.55174    35.46214824 12.07654258]
 [11.84388     0.33033    71.30551    13.59813    35.46214824 12.07654258]
 [12.28782     1.75342    79.69508     1.58847    10.4543308   4.71508207]
 ...
 [20.79023     0.50593    44.67264    14.03005    35.46214824 12.07654258]
 [18.83287     2.71046    69.46467     2.20033    10.4543308   4.71508207]
 [73.42044     5.1794     19.7647      1.62367     5.90487763  4.52358037]]


In [ ]:
print(y_train)

[3 3 2 3 0 2 0 3 1 0 2 2 1 3 2 3 3 3 3 3 3 1 3 2 2 1 3 2 3 3 2 3 0 2 2 3 3
 3 3 2 0 3 3 2 3 3 2 3 3 1 2 3 3 2 3 3 3 3 0 2 2 2 0 3 0 3 0 0 3 1 3 2 2 2
 3 3 3 3 3 3 2 1 2 1 3 1 3 0 1 3 3 1 3 3 3 3 3 2 3 3 2 0 2 3 3 3 3 0 3 3 2
 3 1 3 2 3 0 3 2 2 3 3 3 3 2 1 3 2 1 3 3 0 3 2 3 1 2 1 0 1 3 3 0 2 3 3 2 3
 3 2 3 2 3 3 1 2 3 3 3 2 2 1 1 3 3 2 3 3 3 3 2 3 2 1 3 3 3 0 2 1 3 0 3 2 3
 3 1 3 3 2 1 1 3 2 2 2 0 3 3 3 2 3 3 2 2 1 2 2 3 2 3 3 3 3 2 2 1 3 1 3 3 2
 1 2 1 2 2 1 0 0 2 1 2 0 0 1 3 2 3 3 3 2 3 3 1 1 3 3 2 1 1 2 3 2 0 2 3 1 0
 2 1 0 0 3 3 3 3 3 2 2 3 3 3 3 3 3 1 1 3 2 0 0 0 2 3 3 3 0 0 0 3 3 1 2 3 1
 0 3 1 3 1 0 0 1 2 3 1 3 0 3 0 3 3 1 2 1 1 2 3 2 2 3 3 3 2 3 3 1 0 0 3 3 3
 0 2 1 3 3 1 3 2 2 2 3 3 3 3 3 1 0 2 0 3 3 3 3 3 3 3 3 3 3 2 3 3 0 3 3 0 3
 0 1 2 1 3 3 0 3 3 3 0 2 3 1 3 1 3 0 3 1 0 2 3 3 2 3 3 2 1 3 2 3 2 3 2 3 3
 3 2 2 1 0 3 3 0 2 0 3 2 0 3 3 2 3 3 3 3 3 1 2 1 1 3 1 2 3 3 3 3 3 2 3 2 0
 3 2 3 0 2 2 1 2 3 3 2 3 3 2 3 2 2 3 0 3 1 3 1 1 3 1 1 3 0 3 2 3 0 2 3 2 3
 1 3 1 0 2 2 3 1 3 2 0 3 

In [ ]:
print(X_test)

[[7.79753000e+00 3.24340000e-01 6.32256000e+01 2.27862400e+01
  5.82066327e+01 1.44106155e+01]
 [3.50761900e+01 1.10357400e+01 3.49278600e+01 1.89602100e+01
  7.77365833e+00 1.54313552e+00]
 [1.34241600e+01 3.22970000e-01 7.35436600e+01 1.24903000e+01
  5.82066327e+01 1.44106155e+01]
 ...
 [1.27456647e-01 1.64450867e-01 6.76589595e-01 1.15606900e-03
  3.47372817e+00 4.56380750e+00]
 [7.65530600e+01 1.61469000e+00 1.28941600e+01 2.24677000e+00
  5.90487763e+00 4.52358037e+00]
 [6.25398000e+00 2.95260000e-01 4.97076300e+01 4.37431200e+01
  3.54621482e+01 1.20765426e+01]]


In [ ]:
print(y_test)

[3 1 3 3 3 3 3 3 3 3 3 3 1 3 2 3 3 1 1 0 1 3 3 2 2 2 2 3 3 2 1 3 3 3 3 3 3
 3 2 2 2 2 3 2 3 2 3 2 3 3 3 1 3 3 3 3 2 3 3 0 2 2 2 2 2 2 2 3 2 3 3 2 3 3
 2 1 1 1 0 3 0 2 3 2 3 2 0 3 0 3 3 2 0 0 1 1 3 3 3 3 2 3 1 3 1 2 3 2 3 2 2
 1 1 3 3 2 2 2 2 1 2 3 3 1 3 3 3 0 3 3 3 3 3 3 3 3 3 3 3 1 3 0 2 3 2 2 3 3
 3 1 2 1 3 0 2 3 2 3 3 3 3 3 3 3 2 1 2 3 1 0 3 0 3 1 0 3 2 3 2 3 3 1 3 3 3
 3 2 2 3 3 3 1 0 2 3 0 3 0 2 3 3 3 3 1 2 1 2 3 3 2 2 1 3 3 3 3 2 3 2 3 2 3
 2 3 3 3 1 3 1 2 3 0 3 3 2 1 3 0 1 3 2 1 3 2 3 1 2 3]


## Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 3]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [3 3]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [3 3]
 [2 2]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [2 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [2 2]
 [2 1]
 [1 1]
 [1 1]
 [0 0]
 [3 3]
 [0 0]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [0 0]
 [3 3]
 [0 0]
 [3 3]
 [3 3]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [3 3]
 [1 1]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [3 3]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [0 0]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [0 0]
 [2 2]

## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 18   0   0   1]
 [  0  30   5   0]
 [  0   0  65   0]
 [  0   0   0 129]]


0.9758064516129032