<a href="https://colab.research.google.com/github/AhmedAboushanab/Machine-learning-models/blob/main/random_forest_classification_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Random Forest Classification

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Total.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


**Encoding categorical output**

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

## Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [5]:
print(X_train)

[[35.099       0.13618    59.21308     5.55174    35.46214824 12.07654258]
 [11.84388     0.33033    71.30551    13.59813    35.46214824 12.07654258]
 [12.28782     1.75342    79.69508     1.58847    10.4543308   4.71508207]
 ...
 [20.79023     0.50593    44.67264    14.03005    35.46214824 12.07654258]
 [18.83287     2.71046    69.46467     2.20033    10.4543308   4.71508207]
 [73.42044     5.1794     19.7647      1.62367     5.90487763  4.52358037]]


In [6]:
print(y_train)

[3 3 2 3 0 2 0 3 1 0 2 2 1 3 2 3 3 3 3 3 3 1 3 2 2 1 3 2 3 3 2 3 0 2 2 3 3
 3 3 2 0 3 3 2 3 3 2 3 3 1 2 3 3 2 3 3 3 3 0 2 2 2 0 3 0 3 0 0 3 1 3 2 2 2
 3 3 3 3 3 3 2 1 2 1 3 1 3 0 1 3 3 1 3 3 3 3 3 2 3 3 2 0 2 3 3 3 3 0 3 3 2
 3 1 3 2 3 0 3 2 2 3 3 3 3 2 1 3 2 1 3 3 0 3 2 3 1 2 1 0 1 3 3 0 2 3 3 2 3
 3 2 3 2 3 3 1 2 3 3 3 2 2 1 1 3 3 2 3 3 3 3 2 3 2 1 3 3 3 0 2 1 3 0 3 2 3
 3 1 3 3 2 1 1 3 2 2 2 0 3 3 3 2 3 3 2 2 1 2 2 3 2 3 3 3 3 2 2 1 3 1 3 3 2
 1 2 1 2 2 1 0 0 2 1 2 0 0 1 3 2 3 3 3 2 3 3 1 1 3 3 2 1 1 2 3 2 0 2 3 1 0
 2 1 0 0 3 3 3 3 3 2 2 3 3 3 3 3 3 1 1 3 2 0 0 0 2 3 3 3 0 0 0 3 3 1 2 3 1
 0 3 1 3 1 0 0 1 2 3 1 3 0 3 0 3 3 1 2 1 1 2 3 2 2 3 3 3 2 3 3 1 0 0 3 3 3
 0 2 1 3 3 1 3 2 2 2 3 3 3 3 3 1 0 2 0 3 3 3 3 3 3 3 3 3 3 2 3 3 0 3 3 0 3
 0 1 2 1 3 3 0 3 3 3 0 2 3 1 3 1 3 0 3 1 0 2 3 3 2 3 3 2 1 3 2 3 2 3 2 3 3
 3 2 2 1 0 3 3 0 2 0 3 2 0 3 3 2 3 3 3 3 3 1 2 1 1 3 1 2 3 3 3 3 3 2 3 2 0
 3 2 3 0 2 2 1 2 3 3 2 3 3 2 3 2 2 3 0 3 1 3 1 1 3 1 1 3 0 3 2 3 0 2 3 2 3
 1 3 1 0 2 2 3 1 3 2 0 3 

In [7]:
print(X_test)

[[7.79753000e+00 3.24340000e-01 6.32256000e+01 2.27862400e+01
  5.82066327e+01 1.44106155e+01]
 [3.50761900e+01 1.10357400e+01 3.49278600e+01 1.89602100e+01
  7.77365833e+00 1.54313552e+00]
 [1.34241600e+01 3.22970000e-01 7.35436600e+01 1.24903000e+01
  5.82066327e+01 1.44106155e+01]
 ...
 [1.27456647e-01 1.64450867e-01 6.76589595e-01 1.15606900e-03
  3.47372817e+00 4.56380750e+00]
 [7.65530600e+01 1.61469000e+00 1.28941600e+01 2.24677000e+00
  5.90487763e+00 4.52358037e+00]
 [6.25398000e+00 2.95260000e-01 4.97076300e+01 4.37431200e+01
  3.54621482e+01 1.20765426e+01]]


In [8]:
print(y_test)

[3 1 3 3 3 3 3 3 3 3 3 3 1 3 2 3 3 1 1 0 1 3 3 2 2 2 2 3 3 2 1 3 3 3 3 3 3
 3 2 2 2 2 3 2 3 2 3 2 3 3 3 1 3 3 3 3 2 3 3 0 2 2 2 2 2 2 2 3 2 3 3 2 3 3
 2 1 1 1 0 3 0 2 3 2 3 2 0 3 0 3 3 2 0 0 1 1 3 3 3 3 2 3 1 3 1 2 3 2 3 2 2
 1 1 3 3 2 2 2 2 1 2 3 3 1 3 3 3 0 3 3 3 3 3 3 3 3 3 3 3 1 3 0 2 3 2 2 3 3
 3 1 2 1 3 0 2 3 2 3 3 3 3 3 3 3 2 1 2 3 1 0 3 0 3 1 0 3 2 3 2 3 3 1 3 3 3
 3 2 2 3 3 3 1 0 2 3 0 3 0 2 3 3 3 3 1 2 1 2 3 3 2 2 1 3 3 3 3 2 3 2 3 2 3
 2 3 3 3 1 3 1 2 3 0 3 3 2 1 3 0 1 3 2 1 3 2 3 1 2 3]


## Training the Random Forest Classification model on the Training set

In [9]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

## Predicting the Test set results

In [10]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 3]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [3 3]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [3 3]
 [2 2]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [2 2]
 [3 3]
 [3 3]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [3 3]
 [0 0]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [0 0]
 [3 3]
 [0 0]
 [3 3]
 [3 3]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [2 2]
 [3 3]
 [1 1]
 [3 3]
 [1 1]
 [2 2]
 [3 3]
 [2 2]
 [3 3]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [3 3]
 [3 3]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [3 3]
 [3 3]
 [0 0]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [1 1]
 [3 3]
 [0 0]
 [2 2]

## Making the Confusion Matrix

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 19   0   0   0]
 [  0  35   0   0]
 [  0   0  65   0]
 [  0   0   0 129]]


1.0